---
apiVersion: v1
kind: Secret
metadata:
  name: testsecret-env
  namespace: stage
type: Opaque
data:
  username: YWRtaW4K
  password: c29tZV9wYXNzd29yZAo=

---
apiVersion: v1
kind: Secret
metadata:
  name: testsecret-yaml
  namespace: stage
type: Opaque
stringData:
  config.yaml: |
    apiUrl: "https://secret.site.tt/api/v1"
    username: <admin>
    password: <some_password>